algoritmo "HABILITAÇÂO"
// Função : My first conversation
// Autor : Daniel Bom
// Data : 13/02/2019
var
        nome: caractere
        idade: inteiro
inicio
      escreval ("Qual é seu nome ?")
      leia(nome)
      escreval("Oi ", nome, "! Seja bem-vindo!")
      
      escreva("Digite a sua idade: ")
      leia (idade)
      
      se idade >= 18 entao
         escreva("Já pode tirar a habilitação")
      senao
         escreva("Favor aguardar")
      fimse
      

fimalgoritmo
